name: GitHub Actions Demo
on: [push]
jobs:
  #steps:
  #  -name: build
  #  -name: test
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Build non serve in in githu
        uses: actions/checkout@v3
        #script: echo "Hello Word"
        run: echo "Hello Word"

  # test:
  #   image:
  #   steps: 
  #     #- name: test
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #     #- image: python
  #     - run: pip install -r requirements.txt
  #     # script:
  #     # - pytest
  #     - run: pytest

  # delivery-job:
  #   steps: 
  #     - name: delivery
  #     - tags:
  #     - tags
  #   run:
  #     - docker image build -t pyapp .
  #     - docker image save pyapp |
