name: GitHub Actions Demo
on: [push]
jobs:
  #steps:
  #  -name: build
  #  -name: test
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: build
      - uses: actions/checkout@v3
      #script: echo "Hello Word"
      - run: echo "Hello Word"

  # test-job:
  #   image:
  #   steps: 
  #     - name: test
  #     - image: python
  #     - run: pip install -r requirements.txt
  #     # script:
  #     # - pytest
  #     - run: pytest

  # delivery-job:
  #   steps: 
  #     - name: delivery
  #     - tags:
  #     - tags
  #   run:
  #     - docker image build -t pyapp .
  #     - docker image save pyapp |
